### ISSUE TITLE
Uncaught Error: Actions must be plain objects. Use custom middleware for async actions

### ISSUE THREAD

**Issue by cfpinto** [LaunchPadLab/redux-flash#10]
This error occurs when using your middleware in conjunction with redux-sagas. Do you have any idea what it means?

**Comment by dpikt** [comment]
This library is built with a peer dependency on `redux-thunk`. Try adding the `redux-thunk` middleware to your store: https://github.com/gaearon/redux-thunk#installation

**Comment by cfpinto** [comment]
That would explain it. I'm not using thunk, I'm using redux-sagas. Ended up creating a custom middleware to take care of the problem. I'll close the ticket. thanks
