### ISSUE TITLE
getLatestMessage not working

### ISSUE THREAD

**Issue by aeciolevy** [LaunchPadLab/redux-flash#15]
Hello, I can not import the library.

getLatestMessage is breaking:
I am getting this error:
Error: redux-flash: state not found. Did you remember to attach the reducer at key `flash`?

**Comment by dpikt** [comment]
Is the flash reducer included in your root reducer as per the quickstart [example](https://github.com/LaunchPadLab/redux-flash#example)?

**Comment by aeciolevy** [comment]
It is, but I did not apply the middleware, should I apply it?

This is the code (reducer/index.js): 
```js
import { combineReducers } from 'redux';
import { reducer as formReducer } from 'redux-form';
import auth from './auth';
import fetch from './fetching';
import competition from './competition'
import { reducer as flashReducer } from 'redux-flash';

const rootReducer = combineReducers({
    auth,
    competition,
    fetch,
    flashReducer,
    form: formReducer,
})

export default rootReducer;
```

should I apply the flash middleware here as well?

```js
const enhancer = composeEnhancers( applyMiddleware(thunkMiddleware));
```

**Comment by dpikt** [comment]
Yes, you will need to apply the middleware as well. This particular error, though, is coming from the name given to the reducer in the `combineReducers()` call:

```diff
const rootReducer = combineReducers({
    auth,
    competition,
    fetch,
-   flashReducer,
+   flash: flashReducer,
    form: formReducer,
})

```

This should fix your issue.

**Comment by aeciolevy** [comment]
Thanks. It works.

This is because you use flash key on the selectors, right?
// First, include the flash reducer keyed under 'flash' in your root reducer

**Comment by dpikt** [comment]
Exactly! :)
