### ISSUE TITLE
Component to display flash-messages in Material-UI

### ISSUE THREAD

**Issue by chomamateusz** [LaunchPadLab/redux-flash#27]
Hi!

Great work! 

I've created a component that displays flash messages in Material-UI Snackbars/Toasts.

Its published on BIT -> https://bit.dev/amazingdesign/react-redux-mui-starter/display-flash-toasts

Check it out.

Maybe you wanna put it in the README? I can do a section and PR that.

**Comment by chawes13** [comment]
Apologies for the delayed response! Thanks so much for sharing. At this time, we're not interested in including a separate usages section for other component libraries.
